---


- name: Create resource group
  azure_rm_resourcegroup:
    name: "{{ azure_resource_group }}"
    location: "{{ azure_location }}"

#- name: Create the root DNS zone
#  azure_rm_dnszone:
#    name: "{{ azure_dns_zone }}"
#    resource_group: "{{ azure_resource_group }}"

#- name: Create private DNS
#  azure_rm_dnszone:
#    resource_group: "{{ azure.resource_group }}"
#    name: openshift.local
#    registration_virtual_networks: openshift-virtual-network
#    type: private
