---

- name: '[INSTALL_CONFIG] Installing Openshift Cluster...'
  shell:
    cmd: "{{ user_path }}/openshift-install create cluster --dir {{ user_path }} --log-level debug"
    creates: "{{ user_path }}/auth"

- name: '[INSTALL_CONFIG] Check pid of openshift-install'
  pids:
    name: openshift-install
  register: installer_pids

- name: '[INSTALL_CONFIG] Wait for the main installer to finish - may take around 25 minutes'
  wait_for:
    path: "{{ user_path }}/auth/kubeconfig"
    state: present
    timeout: 5400

- name: '[INSTALL_CONFIG] Wait for the Bootstrap'
  shell:
    cmd: "{{ user_path }}/openshift-install wait-for bootstrap-complete --dir {{ user_path }}"

- name: '[INSTALL_CONFIG] Wait for the cluster'
  shell:
    cmd: "{{ user_path }}/openshift-install wait-for install-complete --dir {{ user_path }}"

- name: '[INSTALL_CONFIG] Copy the Kubeconfig to the know location'
  copy:
    src: "{{ user_path }}/auth/kubeconfig"
    dest: "{{ local_kubeconfig }}"
  when:
    - local_kubeconfig is defined

- name: '[INSTALL_CONFIG] Gzip Install files'
  archive:
    path: "{{ user_path }}/{{ item }}"
    dest: "{{ tower_path }}/{{ cluster_name }}-{{ ocp_cluster }}-install.gz"
    format: gz
  loop:
    - .openshift_install_state.json
    - .openshift_install.log
    - terraform.tfvars.json
    - terraform.tfstate
    - metadata.json
    - terraform.aws.auto.tfvars.json
    - openshift-install
  when:
    - tower_used is defined
    - tower_used | bool

